// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnM8gLiSTx6QNa9FfjW7r_SWYxqx3j0W0',
    appId: '1:153994932727:web:69da6ad86b7848dc74bef2',
    messagingSenderId: '153994932727',
    projectId: 'si-agen-fire',
    authDomain: 'si-agen-fire.firebaseapp.com',
    storageBucket: 'si-agen-fire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA11-ynCCpwTIBZ0_2wyoQ-QPX35tUWWY0',
    appId: '1:153994932727:android:4cf3ddaccf4a093a74bef2',
    messagingSenderId: '153994932727',
    projectId: 'si-agen-fire',
    storageBucket: 'si-agen-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd9ZWcyaKw7nnsyihsDY_fcGhyTzJytEg',
    appId: '1:153994932727:ios:dfc57cb67d8a112674bef2',
    messagingSenderId: '153994932727',
    projectId: 'si-agen-fire',
    storageBucket: 'si-agen-fire.appspot.com',
    iosClientId: '153994932727-itecpiaa3nsilvipa8su774stscl5141.apps.googleusercontent.com',
    iosBundleId: 'com.siagent.singkawang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd9ZWcyaKw7nnsyihsDY_fcGhyTzJytEg',
    appId: '1:153994932727:ios:dfc57cb67d8a112674bef2',
    messagingSenderId: '153994932727',
    projectId: 'si-agen-fire',
    storageBucket: 'si-agen-fire.appspot.com',
    iosClientId: '153994932727-itecpiaa3nsilvipa8su774stscl5141.apps.googleusercontent.com',
    iosBundleId: 'com.siagent.singkawang',
  );
}
